name: Updating IntactixImageServer.config file.
on:
  push:
    paths:
    - 'workloads/ac15/dv01/custom-config/imageserver/IntactixImageServer.config'
    
jobs:
   build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: "Login to Azure"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Get Secrets From Azure Key Vault"
        uses: Azure/get-keyvault-secrets@v1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          keyvault: "kv-rg-ac15-01-dv-euw-01"
          secrets: 'azure-infra-resource-group-name, azure-infra-storage-acct-name, azure-infra-storage-acct-key, azure-kuberenetes-service-name'
        id: myGetSecretAction
      