name: Updating IntactixImageServer.config file.
on:
  push:
    paths: 
    - 'workloads/imageserver/IntactixImageServer.config'
    types: [closed]

jobs:
   build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: "Login to Azure"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: "Get Secrets From Azure Key Vault"
        uses: Azure/get-keyvault-secrets@v1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          keyvault: "kv136"
          secrets: 'azure-infra-resource-group-name, azure-infra-storage-acct-name, access-key'
        id: myGetSecretAction
      

      - name: Deleting IntactixImageServer.config File From the Azure File Storage.
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage file delete --paths IntactixImageServer.config --share-name imageserver --account-key  ${{ steps.myGetSecretAction.outputs.access-key }} --account-name ${{ steps.myGetSecretAction.outputs.azure-infra-storage-acct-name }}

     