name: Updating IntactixImageServer.config file.
on: [push]
jobs:
   build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: "Login to Azure"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: "Get Secrets From Azure Key Vault"
        uses: Azure/get-keyvault-secrets@v1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          keyvault: "kv136"
          secrets: 'azure-infra-resource-group-name, azure-infra-storage-acct-name, access-key'
        id: myGetSecretAction

      

     