name: Updating IntactixImageServer.config file.
on: [push]
jobs:
   build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: "Login to Azure"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      

     