name: Updating IntactixImageServer.config file.
on: [push]
   
    
jobs:
   build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set the Subscription
        uses: azure/CLI@v1
        with:

          azcliversion: 2.30.0

          inlineScript: |

            az account set --subscription 84b819d9-03ac-4d5a-8b02-0f8cee4c823b

      

     