on: [push]

name: AzurePowerShellLoginSample

jobs:

  build:
    runs-on: windows-latest
    steps:
    
    - name: "Azure Login"
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: "Uploading file to storage account"
      shell: pwsh
      run: azcopy copy 'C:\ImageServer\ImageServerFile.config' 'https://csg100320017998846f.dfs.core.windows.net/fileupload/ImageServerFile.config'