on: [push]

name: AzurePowerShellLoginSample

jobs:

  build:
    runs-on: windows-latest
    steps:
    
    - name: "Azure Login"
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: RunPowerShellScript
      shell: pwsh
      run: |
        PostBuilds/.github/workflows/TestPowershell.ps1